version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deploy:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - run:
              name: Deploy Master to Heroku
              command: |
                git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
    build-test-and-deploy:
      jobs:
        - build-and-test
        - deploy
          requires:
              - build-and-test
            filters:
              branches:
                only: master
