version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
  test:
    executor:
      name: node/default
    steps:
      - run: npm test
  deploy:
    executor:
      name: node/default
    steps:
      - run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
          
